version: 2
jobs:
  build:
    working_directory: ~/opt/self-service/
    docker:
      - image: circleci/python:3.8.1
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/selfservice?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment: # environment variables for the Postgres container.
          POSTGRES_USER: root
          POSTGRES_DB: selfservice
    steps:
      - run: sudo chown -R circleci:circleci /opt/self-service
      - checkout # check out source code to working directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - run:
          command: |
            pip install pipenv
            pipenv install
      - run:
          command: |
            pipenv run python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
