version: 2
jobs:
  build:
    working_directory: ~/opt/self-service/
    docker:
      - image: circleci/python:3.8.1
        environment:
          PIPENV_VENV_IN_PROJECT: true
          SELF_SERVICE_DEV: true
      - image: mockserver/mockserver
        name: mockserver.mockserver
    steps:
      - checkout # check out source code to working directory
      - run: 
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - run: 
          command: |
            sudo apt update
            sudo apt install -y libxml2-dev libxmlsec1-dev libxmlsec1-openssl
      - run:
          command: |
            git submodule update --init --recursive
            cp dynatrace_admin/settings.template.py dynatrace_admin/settings.py
            cp .circleci/user_variables.py framework/user_variables.py
      - run:
          command: |
            pip install pipenv
            pipenv install --dev
            pipenv run python manage.py makemigrations
            pipenv run python manage.py migrate
      - run:
          command: |
            SELF_SERVICE_DEV=TRUE pipenv run python manage.py test
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
